import { args, command, z } from "../../../zcli.ts";
import { config, configPaths } from "../../../config.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const get = command("get", {
  short: "Get a configuration value.",
  commands: subCommands,
  args: args({
    short: "The key to get.",
  }).tuple([z.enum(configPaths)]),
}).run(
  async function* ({ args }) {
    const [key] = args;
    const value = await config.get(key);
    yield value;
  },
);
