// deno-lint-ignore-file no-explicit-any
import { args, command, intl, z } from "../../../zcli.ts";
import { config, configPaths } from "../../../config.ts";

/**
 * This variable is automatically generated by `zcli add`. Do not remove this
 * or change its name unless you're no longer using `zcli add`.
 */
const subCommands: ReturnType<typeof command>[] = [];

export const set = command("set", {
  short: "Set a configuration value.",
  commands: subCommands,
  args: args({
    short: "The key/value pair to set.",
  }).tuple([z.enum(configPaths), z.string()]),
}).run(
  async function* ({ args }) {
    const [key, value] = args;

    try {
      await config.set<any>(key, value);
    } catch (err) {
      if (err instanceof z.ZodError) {
        const formErrors = err.formErrors;

        for (const e of err.errors) {
          if (e.code === z.ZodIssueCode.invalid_enum_value) {
            yield `⛔ Invalid value for key "${
              e.path.join(
                ".",
              )
            }". Expected ${
              intl.list(
                e.options.map((o) => "" + o),
                {
                  type: "disjunction",
                },
              )
            }. Received ${e.received}.`;
          }

          yield `⛔ Invalid value for key "${e.path.join(".")}". ${
            formErrors.fieldErrors[e.path[0]]
          }`;
        }
      }

      Deno.exit(1);
    }

    yield `${key} = ${await config.get(key)}`;
  },
);
