name: Release

on:
  push:
    branches:
      - main
      - next

concurrency: release-${{ github.head_ref }}
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x.x
      
      - name: Install semantic release
        run: npm init -y && npm i semantic-release @google/semantic-release-replace-plugin @semantic-release/exec

      - name: Release
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}